---
title: 'MAGIC AI Workshop (Feb 19-21 2024)'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author:
  - Simon Brewer^[University of Utah, simon.brewer@geog.utah.edu]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: flatly
    df_print: paged
    number_sections: false
    toc: false
    toc_float: false
---

# Agenda

-	Monday morning
    - General introduction (Simon)
    - Introduction to machine learning (Adit)
    - Intro ML exercise: [R notebook][introML_R]|[Python notebook][introML_P]|[Colab notebook][introML_C]
    - Open project discussion (all participants)
- Monday afternoon
    - Introduction to convolutional neural networks (Savanna)
    - Image segmentation (Husile)
    - CNN exercise: [R notebook][CNN_R]|[Python notebook][CNN_P]|[Colab notebook][CNN_C]
    - Project work (groups)
- Tuesday morning
    - Introduction to Natural Language Processing methods (Simon)
    - NLP exercise: [R notebook][NLP_R]|[Python notebook][NLP_P]|[Colab notebook][NLP_C]
    - Project work (groups)
- Tuesday afternoon
    - General MAGIC project discussion (incl. Patagonia field trip)
    - Trip to [Gilbert Geologic Park][gilbert]
- Wednesday morning
    - Possible: Unsupervised methods or discussion on data sources
    - Project work (groups)
    - Workshop wrap-up

# Data

Workshop Google Drive:
https://drive.google.com/drive/folders/1GMEY1fYEj1YMI__u3hU4y6agnrz3ekna?usp=sharing


All files for the exercises can be found [here][gdrive]

# Colab notebooks

https://drive.google.com/file/d/1l7t6iAIHggNFSJ-zoxJZYMYSGDzUBWPT/view?usp=sharing

https://drive.google.com/file/d/1c7Ui7mzJWmAf2KoSaE1wJm6qlgaEgkDh/view?usp=sharing

https://drive.google.com/file/d/1tgcHQvWaYYWk71O3qMJDeTJ3KzdlKUhe/view?usp=sharing


[introML_R]: https://simonbrewer.github.io/MAGIC_AI_Workshop/MAGIC_01_IntroML.html
[introML_P]: https://github.com/simonbrewer/MAGIC_AI_Workshop/blob/main/MAGIC_01_IntroML.ipynb
[introML_C]: https://drive.google.com/file/d/1l7t6iAIHggNFSJ-zoxJZYMYSGDzUBWPT/view?usp=sharing
[CNN_R]: https://simonbrewer.github.io/MAGIC_AI_Workshop/MAGIC_02_CNNS.html
[CNN_P]: https://github.com/simonbrewer/MAGIC_AI_Workshop/blob/main/MAGIC_02_CNNs.ipynb
[CNN_C]: https://drive.google.com/file/d/1c7Ui7mzJWmAf2KoSaE1wJm6qlgaEgkDh/view?usp=sharing
[NLP_R]: https://simonbrewer.github.io/MAGIC_AI_Workshop/MAGIC_03_NLP.html
[NLP_P]: https://github.com/simonbrewer/MAGIC_AI_Workshop/blob/main/MAGIC_03_NLP.ipynb
[NLP_C]: https://drive.google.com/file/d/1tgcHQvWaYYWk71O3qMJDeTJ3KzdlKUhe/view?usp=sharing
[gilbert]: https://geology.utah.gov/map-pub/survey-notes/geosights/g-k-gilbert-geologic-view-park/
[gdrive]: https://drive.google.com/drive/folders/1lp79wJvtis-SDQ2pbZ4Ecgb4CEEawV-Q?usp=drive_link
[wshop]: https://drive.google.com/drive/folders/1GMEY1fYEj1YMI__u3hU4y6agnrz3ekna?usp=sharing